language: node_js
node_js:
  - "6"
  
before_script:
  - wget https://github.com/casperjs/casperjs/tarball/1.1.0.tar.gz -O /tmp/casper.tar.gz
  - tar -xvf /tmp/casper.tar.gz
  - export PATH=$PATH:$PWD/casperjs-1.0.0/bin/
